events.listen('item.registry', event => {


  event.create('salad').food(food => {food.hunger(9).saturation(1)}).displayName('沙拉').maxStackSize(64)
  event.create('valdanium_ingot').displayName('瓦尔丹坭坶锭')
  event.create('valdanium_nugget').displayName('瓦尔丹坭坶粒')
  event.create('double_arrow').displayName('绿色双重箭')
  event.create('wooden_double_arrow').displayName('木制双重箭')
  event.create('double_arrow_cast').displayName('金质双重箭铸模')
  event.create('large_plate_diamond').displayName('钻石 大板')
  event.create('large_plate_netherite').displayName('下界合金 大板')
  event.create('bee').displayName('蜜蜂')
  event.create('rgb_dye').displayName('彩色染料')
  //dna
  event.create('cobblestone_bee_dna').displayName('圆石蜜蜂DNA')
  event.create('andesite_bee_dna').displayName('安山岩蜜蜂DNA')
  event.create('diorite_bee_dna').displayName('闪长岩蜜蜂DNA')
  event.create('dirt_bee_dna').displayName('泥土蜜蜂DNA')
  event.create('granite_bee_dna').displayName('花岗岩蜜蜂DNA')
  event.create('gravel_bee_dna').displayName('沙砾蜜蜂DNA')
  event.create('lava_bee_dna').displayName('熔岩蜜蜂DNA')
  event.create('rgbee_bee_dna').displayName('彩色蜜蜂DNA')
  event.create('sand_bee_dna').displayName('沙子蜜蜂DNA')
  event.create('snowball_bee_dna').displayName('雪球蜜蜂DNA')
  event.create('water_bee_dna').displayName('水蜜蜂DNA')
  event.create('wood_bee_dna').displayName('木材蜜蜂DNA')
  event.create('basalz_dna').displayName('岩石DNA')
  event.create('bee_dna').displayName('蜜蜂DNA')
  event.create('blaze_dna').displayName('烈焰DNA')
  event.create('blitz_dna').displayName('狂风DNA')
  event.create('blizz_dna').displayName('暴雪DNA')
  event.create('empty_dna').displayName('空DNA')
  event.create('enderman_dna').displayName('末影人DNA')
  event.create('shulker_dna').displayName('潜影DNA')
  event.create('guardian_dna').displayName('守护者DNA')
  //dna_creator
  event.create('fishi_bee_dna').displayName('鱼蜜蜂DNA')
  event.create('matter_bee_dna').displayName('物质蜜蜂DNA')

})
