onEvent('item.tooltip', event => {



//Seed Ore
event.add('kubejs:seed_ore', [Text.of('破坏这个以获得种子')])
//drop seed ore
event.add('thermal:rice_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:radish_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:onion_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:corn_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:barley_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:beetroot_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:melon_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:wheat_seeds', [Text.of('你可以从矿石种子和破坏草中得到这个')])
event.add('thermal:hops_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:tomato_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:strawberry_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:peanut_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:green_bean_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:eggplant_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:bell_pepper_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:spinach_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:sadiroot_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:pumpkin_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:blood_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:ender_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:sky_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:earth_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:frost_melon_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:tea_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:seagrass', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:ender_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:sky_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:earth_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:nether_wart', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:blood_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:sea_pickle', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:flax_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:amaranth_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:coffee_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:potato', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:acacia_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:jungle_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:birch_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:spruce_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:oak_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:dark_oak_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:kelp', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:bamboo', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:sugar_cane', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:sweet_berries', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:carrot', [Text.of('你可以从矿石种子中得到这个')])






//Combs
event.add('resourcefulbees:coal_honeycomb', [Text.of('燃烧时间 = 1000')])
event.add('resourcefulbees:coal_honeycomb_block', [Text.of('燃烧时间 = 9000')])
event.add('resourcefulbees:wood_honeycomb', [Text.of('燃烧时间 = 200')])
event.add('resourcefulbees:wood_honeycomb_block', [Text.of('燃烧时间 = 1800')])

//dna
event.add('kubejs:cobblestone_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:fishi_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:diorite_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:dirt_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:granite_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:gravel_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:lava_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:rgbee_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:sand_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:snowball_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:water_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:wood_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:basalz_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:blaze_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:blitz_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:guardian_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:shulker_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:blizz_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:andesite_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:enderman_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:matter_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])

})

events.listen('jei.information', function (event) {

// Recipe JEI


//market
event.add('farmingforblockheads:market', 'You have to reach Game Stage "Market" to get the Crafting Recipe!')
//Seed Ore
event.add('kubejs:seed_ore', [Text.of('Break this to get Seeds')])
//drops seed ore
event.add('thermal:rice_seeds', [Text.of('You can get this from the Seed ')])
event.add('thermal:radish_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:onion_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:corn_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:barley_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:beetroot_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:melon_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:wheat_seeds', [Text.of('你可以从矿石种子和破坏草中得到这个')])
event.add('thermal:hops_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:tomato_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:strawberry_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:peanut_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:green_bean_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:eggplant_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:bell_pepper_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:spinach_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:sadiroot_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:pumpkin_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:blood_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:ender_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:sky_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:earth_slime_grass_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:frost_melon_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:tea_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:seagrass', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:ender_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:sky_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:earth_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:nether_wart', [Text.of('你可以从矿石种子中得到这个')])
event.add('tconstruct:blood_slime_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:sea_pickle', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:flax_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:amaranth_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('thermal:coffee_seeds', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:potato', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:acacia_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:jungle_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:birch_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:spruce_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:oak_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:dark_oak_sapling', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:kelp', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:bamboo', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:sugar_cane', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:sweet_berries', [Text.of('你可以从矿石种子中得到这个')])
event.add('minecraft:carrot', [Text.of('你可以从矿石种子中得到这个')])

//dna
event.add('kubejs:cobblestone_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:fishi_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:diorite_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:dirt_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:granite_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:gravel_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:lava_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:rgbee_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:sand_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:snowball_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:water_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:wood_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:basalz_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:blaze_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:blitz_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:guardian_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:shulker_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:blizz_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:andesite_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:enderman_dna', [Text.of('右键单击DNA生成器上的DNA')])
event.add('kubejs:matter_bee_dna', [Text.of('右键单击DNA生成器上的DNA')])

event.add('minecraft:grass_block', [Text.of('用种子右键单击泥土！它可以是带有标签的种子：Forge:seeds')])

})
